# Generated by Django 4.1.1 on 2022-09-30 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('fecha', models.DateField()),
                ('observacion', models.CharField(max_length=45)),
                ('estado', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia_Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_asitencia', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.CharField(max_length=45)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_asistencia_cedula', to='User.empleado')),
            ],
        ),
    ]
