# Generated by Django 4.1.1 on 2022-09-30 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia_empleado',
            name='observacion',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
