# Generated by Django 4.1.1 on 2022-09-30 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo_materia', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=45)),
                ('estado', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=10)),
                ('sede', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('salon', models.CharField(max_length=10)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('cedula_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_docente', to='User.empleado')),
                ('codigo_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_materia', to='Course.materia')),
            ],
        ),
    ]
