# Generated by Django 4.1.1 on 2022-10-07 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dependencia', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('estado', models.CharField(default='A', max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.ManyToManyField(related_name='fk_dependencia', to='User.cargo')),
                ('cuenta_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_dependencia', to='User.dependencia'),
        ),
    ]
