# Generated by Django 4.1.1 on 2022-10-07 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacacionesEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('estado', models.CharField(default='A', max_length=1)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_vacacion_empleado', to='User.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_final', models.DateTimeField()),
                ('descripcion', models.TextField(max_length=300)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_permiso_empleado', to='User.empleado')),
            ],
        ),
    ]
